"""
Codex平台渲染器 - 渲染Skill为OpenAI Codex格式
==============================================

将通用Skill格式转换为OpenAI Codex可识别的格式。

Codex skill格式要求：
- 配置文件: openai.yaml
- 指令文件: AGENTS.md（可选）
- 变量: 使用{{variable_name}}格式
- 工具: 在配置文件中定义

作者：Ccc
版本：1.0.0
"""

from typing import Dict, List, Any, Optional, Union
from pathlib import Path
import yaml

from skillporter.core.renderer import BaseRenderer
from skillporter.core.schema import UniversalSkill, SkillPlatform, Variable, ToolPermission


class CodexRenderer(BaseRenderer):
    """
    Codex Skill渲染器
    
    将通用Skill格式渲染为OpenAI Codex可识别的格式。
    """
    
    @property
    def platform(self) -> SkillPlatform:
        """返回目标平台类型"""
        return SkillPlatform.CODEX
    
    def render_skill(self, skill: UniversalSkill) -> Dict[str, str]:
        """
        渲染skill为Codex格式
        
        Args:
            skill: 要渲染的UniversalSkill对象
            
        Returns:
            Dict[str, str]: 文件路径到内容的映射
        """
        files = {}
        
        # 1. 生成openai.yaml配置文件
        openai_yaml = self._generate_openai_yaml(skill)
        files["openai.yaml"] = openai_yaml
        
        # 2. 生成AGENTS.md指令文件（如果skill有指令）
        if skill.instructions:
            agents_md = self._generate_agents_md(skill)
            files["AGENTS.md"] = agents_md
        
        # 3. 生成脚本文件
        for script in skill.scripts:
            files[script.path] = script.content
        
        # 4. 生成参考文档
        for ref in skill.references:
            files[ref.path] = ref.content
        
        return files
    
    def render_to_file(self, skill: UniversalSkill, file_path: Union[str, Path]) -> None:
        """
        渲染skill并保存到单个文件
        
        对于Codex，这会生成一个openai.yaml文件。
        
        Args:
            skill: 要渲染的skill对象
            file_path: 输出文件路径
        """
        if not self.validate_before_render(skill):
            errors = self.get_errors()
            raise RuntimeError(f"Validation failed: {'; '.join(errors)}")
        
        # 应用转换
        transformed = self.apply_transforms(skill)
        
        # 生成内容
        content = self._generate_openai_yaml(transformed)
        
        # 写入文件
        self.write_file(content, file_path)
    
    def render_to_directory(self, skill: UniversalSkill, dir_path: Union[str, Path]) -> None:
        """
        渲染整个skill到目录
        
        会创建完整的目录结构：
        {skill-name}/
        ├── openai.yaml
        ├── AGENTS.md（可选）
        ├── scripts/
        └── references/
        
        Args:
            skill: 要渲染的skill对象
            dir_path: 输出目录路径
        """
        if not self.validate_before_render(skill):
            errors = self.get_errors()
            raise RuntimeError(f"Validation failed: {'; '.join(errors)}")
        
        # 应用转换
        transformed = self.apply_transforms(skill)
        
        # 创建目录
        path = Path(dir_path)
        path.mkdir(parents=True, exist_ok=True)
        
        # 生成所有文件
        files = self.render_skill(transformed)
        
        # 写入文件
        for file_path, content in files.items():
            full_path = path / file_path
            self.write_file(content, full_path)
    
    def _generate_openai_yaml(self, skill: UniversalSkill) -> str:
        """
        生成openai.yaml配置文件内容
        
        Args:
            skill: skill对象
            
        Returns:
            str: openai.yaml文件内容
        """
        # 准备配置数据
        config = self._prepare_config(skill)
        
        # 生成YAML字符串
        yaml_str = yaml.dump(config, default_flow_style=False, allow_unicode=True)
        
        # 添加文件头注释
        header = f"""# OpenAI Codex Skill Configuration
# Skill: {skill.name}
# Generated by SkillPorter

"""
        
        return header + yaml_str
    
    def _generate_agents_md(self, skill: UniversalSkill) -> str:
        """
        生成AGENTS.md指令文件内容
        
        Args:
            skill: skill对象
            
        Returns:
            str: AGENTS.md文件内容
        """
        # 准备YAML前言
        yaml_data = {
            "id": skill.id,
            "name": skill.name,
            "description": skill.description
        }
        
        if skill.description_zh:
            yaml_data["description_zh"] = skill.description_zh
        if skill.description_en:
            yaml_data["description_en"] = skill.description_en
        if skill.version:
            yaml_data["version"] = skill.version
        if skill.author:
            yaml_data["author"] = skill.author
        if skill.tags:
            yaml_data["tags"] = skill.tags
        
        # 生成YAML字符串
        yaml_str = yaml.dump(yaml_data, default_flow_style=False, allow_unicode=True)
        
        # 生成完整内容
        content = f"---\n{yaml_str}---\n\n{skill.instructions}"
        
        return content
    
    def _prepare_config(self, skill: UniversalSkill) -> Dict[str, Any]:
        """
        准备openai.yaml配置数据
        
        Args:
            skill: skill对象
            
        Returns:
            Dict[str, Any]: 配置数据
        """
        # 基础字段
        config = {
            "id": skill.id,
            "name": skill.name,
            "description": skill.description
        }
        
        # 可选字段
        if skill.description_zh:
            config["description_zh"] = skill.description_zh
        if skill.description_en:
            config["description_en"] = skill.description_en
        if skill.version:
            config["version"] = skill.version
        if skill.author:
            config["author"] = skill.author
        if skill.tags:
            config["tags"] = skill.tags
        
        # 变量定义（parameters）
        if skill.variables:
            parameters = {}
            for var in skill.variables:
                param_config = {
                    "type": var.type.value if var.type else "string",
                    "required": var.required,
                    "description": var.description or f"Variable: {var.name}"
                }
                if var.default is not None:
                    param_config["default"] = var.default
                parameters[var.name] = param_config
            config["parameters"] = parameters
        
        # 工具权限
        if skill.allowed_tools:
            tools = []
            for tool in skill.allowed_tools:
                if tool.description:
                    tools.append({
                        "name": tool.name,
                        "category": tool.category,
                        "description": tool.description
                    })
                else:
                    tools.append(tool.name)
            config["tools"] = tools
        
        # 指令（简短版本，完整指令在AGENTS.md中）
        if skill.instructions:
            # 提取指令的前200个字符作为摘要
            instruction_summary = skill.instructions[:200]
            if len(skill.instructions) > 200:
                instruction_summary += "..."
            config["instruction_summary"] = instruction_summary
        
        # 平台特有字段
        codex_overrides = skill.get_platform_override(SkillPlatform.CODEX)
        if codex_overrides:
            config.update(codex_overrides)
        
        return config
    
    def get_variable_mapping(self) -> Dict[str, str]:
        """
        获取变量映射规则
        
        Codex使用{{variable_name}}格式。
        
        Returns:
            Dict[str, str]: 源变量 -> 目标变量的映射
        """
        return {
            # 从通用格式到Codex格式
            "$ARGUMENTS": "{{args}}",
            "$CONTEXT": "{{context}}",
            "$FILE_PATH": "{{file_path}}",
            "$SELECTION": "{{selection}}",
            "$WORKSPACE": "{{workspace}}",
            "$USER": "{{user}}"
        }
    
    def get_tool_mapping(self) -> Dict[str, str]:
        """
        获取工具名称映射
        
        Codex使用特定的工具名称。
        
        Returns:
            Dict[str, str]: 源工具名 -> 目标工具名的映射
        """
        return {
            # 从通用格式到Codex格式
            "Read": "read_file",
            "Write": "write_file",
            "Edit": "edit_file",
            "Bash": "execute_shell",
            "Glob": "list_files",
            "Grep": "search_content",
            "AskUserQuestion": "ask_user",
            "WebFetch": "fetch_url",
            "WebSearch": "search_web"
        }
    
    def get_path_mapping(self) -> Dict[str, str]:
        """
        获取路径映射
        
        Codex使用~/.codex/skills/路径。
        
        Returns:
            Dict[str, str]: 源路径 -> 目标路径的映射
        """
        return {
            "~/.workbuddy/skills/": "~/.codex/skills/",
            "~/.claude/skills/": "~/.codex/skills/"
        }
    
    def platform_specific_validation(self, skill: UniversalSkill) -> List[str]:
        """
        Codex平台特定的验证逻辑
        
        Args:
            skill: 要验证的skill对象
            
        Returns:
            List[str]: 错误消息列表
        """
        errors = []
        
        # 注意：变量格式检查已移除，因为变量会在apply_transforms中自动转换
        # 源skill可能使用$ARGUMENTS格式，但会被转换为{{args}}格式
        
        # 检查工具名称（警告，不是错误）
        valid_tools = [
            "read_file", "write_file", "edit_file", "list_files",
            "search_files", "search_content", "execute_shell", "run_command",
            "fetch_url", "search_web", "ask_user", "get_input"
        ]
        
        for tool in skill.allowed_tools:
            if tool.name not in valid_tools:
                # 这是一个警告，不是错误
                self.warnings.append(f"Tool '{tool.name}' may not be available in Codex")
        
        return errors


# 注册渲染器
from skillporter.core.renderer import register_renderer
register_renderer(CodexRenderer())